name: wybuild
description: WyBuild - automatic Android build setup and GitHub Actions build platform.
publish_to: "none"
version: 1.0.1+2
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
